# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030987221f488c6dcec106666073b740abd9922541612837b838653c8efc3ad15698c7de0ab107233d23ad601905a5aae0c27fbd09870a270001653b70a9d897

test:
  secret_key_base: 2556ae81229e6280f52eb91b2f4e61eda0881ac20e14d28f9fbfe07b03038b4ddf8896d4283f88e325725f6a7e0af09c692c715227513e4b2a661f8f290aecf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
